"""The checked-in venue tables (e.g. `data/cfb_venues.json`): their rows, how they are
read and written, and how they become a `VenueCatalog`.

A table is generated by `scripts/generate_cfb_venues.py` and reviewed in PRs, so the file
is deterministic (sorted, fixed number formats, no timestamps) to keep diffs small, and
`parse_table` is strict - a malformed table fails loudly rather than quietly dropping a
venue's weather report.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from dataclasses import dataclass
from importlib import resources

from messy_weather_sports_bot.venues import StadiumInfo, VenueCatalog

SCHEMA_VERSION = 1

COORDINATE_DECIMALS = 5
"""About a metre - far finer than a forecast grid cell, and stable across regenerations."""

PRECISIONS = ("stadium", "other", "manual")
"""How a row's coordinates were found: matched to a stadium (`stadium`), matched to some
other sports venue (`other`: a sports centre, a pitch), or entered by hand (`manual`)."""


@dataclass(frozen=True)
class VenueRow:
    id: str
    """ESPN's venue id - the key a game's venue is looked up by."""
    name: str
    latitude: float
    longitude: float
    is_covered: bool
    city: str
    state: str
    """Two-letter state code. `city` and `state` are review metadata, not used to match."""
    precision: str
    source: str
    """Where the coordinates came from (`nfl_catalog`, `photon:W123`, `manual`), so a
    reviewer knows what to check."""
    aliases: tuple[str, ...] = ()

    def to_stadium(self) -> StadiumInfo:
        return StadiumInfo(
            self.name,
            self.latitude,
            self.longitude,
            self.is_covered,
            venue_id=self.id,
            aliases=self.aliases,
        )

    def to_json(self) -> dict:
        return {
            "aliases": list(self.aliases),
            "city": self.city,
            "id": self.id,
            "is_covered": self.is_covered,
            "latitude": round(self.latitude, COORDINATE_DECIMALS),
            "longitude": round(self.longitude, COORDINATE_DECIMALS),
            "name": self.name,
            "precision": self.precision,
            "source": self.source,
            "state": self.state,
        }


def id_order(venue_id: str) -> tuple[int, int, str]:
    """Sort key for venue ids: ESPN's are numeric strings, ordered numerically, with any
    other id after them."""
    return (0, int(venue_id), venue_id) if venue_id.isdigit() else (1, 0, venue_id)


def dump_table(rows: Iterable[VenueRow]) -> str:
    """The table as JSON text: rows sorted by id, keys sorted, trailing newline."""
    payload = {
        "schema_version": SCHEMA_VERSION,
        "venues": [row.to_json() for row in sorted(rows, key=lambda row: id_order(row.id))],
    }
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _require(row: dict, key: str, kind: type, where: str):
    value = row.get(key)
    # bool is an int subclass: a stray `true` must not pass for a number.
    if not isinstance(value, kind) or (kind is not bool and isinstance(value, bool)):
        raise ValueError(f"{where}: {key!r} must be {kind.__name__}, got {value!r}")
    return value


def _require_text(row: dict, key: str, where: str) -> str:
    value = _require(row, key, str, where)
    if not value.strip():
        raise ValueError(f"{where}: {key!r} must not be blank")
    return value


def _require_number(row: dict, key: str, where: str, limit: float) -> float:
    value = row.get(key)
    if not isinstance(value, int | float) or isinstance(value, bool):
        raise ValueError(f"{where}: {key!r} must be a number, got {value!r}")
    if not -limit <= value <= limit:
        raise ValueError(f"{where}: {key!r} out of range: {value!r}")
    return float(value)


def parse_table(text: str) -> list[VenueRow]:
    """Parse and validate a table. Raises ValueError, naming the row, if anything is
    malformed - an unknown schema version, a missing field, a duplicate id."""
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"venue table is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError("venue table must be a JSON object")
    if payload.get("schema_version") != SCHEMA_VERSION:
        raise ValueError(
            f"unsupported venue table schema_version {payload.get('schema_version')!r} "
            f"(expected {SCHEMA_VERSION})"
        )
    venues = payload.get("venues")
    if not isinstance(venues, list):
        raise ValueError("venue table 'venues' must be a list")

    rows: list[VenueRow] = []
    seen: set[str] = set()
    for index, raw in enumerate(venues):
        if not isinstance(raw, dict):
            raise ValueError(f"venues[{index}] must be an object")
        where = f"venues[{index}] ({raw.get('id')!r})"
        venue_id = _require_text(raw, "id", where)
        if venue_id in seen:
            raise ValueError(f"{where}: duplicate venue id")
        seen.add(venue_id)
        precision = _require_text(raw, "precision", where)
        if precision not in PRECISIONS:
            raise ValueError(f"{where}: 'precision' must be one of {PRECISIONS}, got {precision!r}")
        aliases = raw.get("aliases", [])
        if not isinstance(aliases, list) or not all(isinstance(a, str) for a in aliases):
            raise ValueError(f"{where}: 'aliases' must be a list of strings")
        rows.append(
            VenueRow(
                id=venue_id,
                name=_require_text(raw, "name", where),
                latitude=_require_number(raw, "latitude", where, 90),
                longitude=_require_number(raw, "longitude", where, 180),
                is_covered=_require(raw, "is_covered", bool, where),
                city=_require_text(raw, "city", where),
                state=_require_text(raw, "state", where),
                precision=precision,
                source=_require_text(raw, "source", where),
                aliases=tuple(aliases),
            )
        )
    return rows


def catalog_from_rows(rows: Iterable[VenueRow]) -> VenueCatalog:
    """A catalog that finds a venue by its ESPN id alone. A name is no guide at this
    scale - towns share a "Memorial Stadium" - so an unknown id is reported as drift
    rather than matched to another town's weather. Unlike the NFL's there's no
    team-to-stadium fallback either: college teams play at neutral sites too often to
    guess."""
    return VenueCatalog((row.to_stadium() for row in rows), match_names=False)


def load_packaged_table(filename: str) -> list[VenueRow]:
    """Read a table shipped inside the package's `data/` directory."""
    text = resources.files("messy_weather_sports_bot").joinpath("data", filename).read_text("utf-8")
    return parse_table(text)
